### ISSUE TITLE
Let troops set up a radio beacon

### ISSUE THREAD

**Issue by audax** [shagratdcs/DCS-Medevac#2]
See: http://forums.eagle.ru/showpost.php?p=2389257&postcount=277
- [x] Radio beacons for all troops
- [x] Randomize between beacon, coordinates or both

**Comment by shagratdcs** [comment]
it seems more realistic, we could also reduce MGRS coordinates accuracy (LM123 123 - 100m precision is enough) and have pilots ONLY use beacons and smoke...no coordinates.

What do think?

**Comment by audax** [comment]
Sounds good, will do.

**Comment by audax** [comment]
The precision for coordinates is now configurable and I introduced a chance to set up a radio beacon, currently set to 50%. I think that should be fine.
