### ISSUE TITLE
Troop should wait in defensive position until rescued

### ISSUE THREAD

**Issue by audax** [shagratdcs/DCS-Medevac#3]
Let them stay low until they start running to the helicopter.

**Comment by shagratdcs** [comment]
Not sure if that can esaily be added... there is a setting for "alarm state" red/green that could make them take a defensive stance, but IIRC it prevents the troops from moving most of the time...
I would see this as a B priority issue. If in danger (enemy near) or attacked/hit, troops react and defend themselves anyway.

**Comment by audax** [comment]
Good point. Maybe this is something for EDGE…
