### ISSUE TITLE
Let infantry ask for evac when they have <25% strength

### ISSUE THREAD

**Issue by audax** [shagratdcs/DCS-Medevac#6]
Maybe we can spawn a new wounded group and let the old group continue fighting.

**Comment by shagratdcs** [comment]
Maybe, the issue with "spawning" new infantry groups, when an infantry group falls below 25% strength could lead to an infinite loop, spawning dozens of infantry groups...
To keep it generic enough, it would be better to inject the existing group name into the Evacuation procedure.
-add the group name to woundedgroups
-handle the remaining troops as a normal medevac

**Comment by shagratdcs** [comment]
Ok, I've got an idea: function medevac.initSARForGroup(_downedGroup, _pilot) initiates the medevac for a newly spawned group after a vehicle is destroyed.
Now if we would call the function with a groupname to extract after evaluating that groups strength is below 25% (or a variable value) we only need to get a table of "potential" groups by name.
I think this can be accessed as a global table (ExtGroups{}) from the CTTS script directly.

So check if ExtGroups{} exists, if yes, monitor health using Group.getInitialSize - Group.getSize to monitor the percentage of survivng units and add the group to the medevac table with medevac.initSARForGroup(_downedGroup, _pilot)

What do you think?

**Comment by audax** [comment]
https://github.com/shagratdcs/DCS-Medevac/blob/master/Medevac_CSAR.lua#L1394
medevac.injectWoundedGroup(_groupName,_isPilot) can do this now.

**Comment by shagratdcs** [comment]
Basic functionality works now!. Generic injectWoundedGroup for infantry groups that are NOT woundedGroups  from Medevac script... Still some issues to iron out, before I will commit the change.

**Comment by shagratdcs** [comment]
Works, parameters can be excluded for infantry
