### ISSUE TITLE
Killed MEDEVAC still has wounded loaded after respawn in MP

### ISSUE THREAD

**Issue by shagratdcs** [shagratdcs/DCS-Medevac#9]
After I got shot down by Audax, I respawned in the same Huey and when I tried to pick up another group, I got the "Crammed" message and couldn't board the new group.
Neither was it possible to unload the wounded aboard at the FARP/MASH.

**Comment by ciribob** [comment]
Line 842 which is currently  medevac.inTransitGroups[_args[1]] = nil

Can be changed to medevac.inTransitGroups[_args.heliName] = nil

which should fix it

**Comment by audax** [comment]
Indeed. I changed that one to a table with string keys and forgot to change that one.
Since I didn't destroy my helicopter in the tests…

I'll test it tomorrow and send another pull request :D

**Comment by shagratdcs** [comment]
Nice! Always the small things... :+1:

**Comment by audax** [comment]
I couldn't wait to fix it :D

**Comment by ciribob** [comment]
lol thanks! :) :+1:
